### ISSUE TITLE
cannot set SMTP addr with env var

### ISSUE THREAD

**Issue by unixslayer** [mailhog/mhsendmail#25]
With mhsendmail installed on application container and MailHog on another, I'm unable to set smtp addr using ENV vars. mhsendmail keeps trying to use localhost:1025. 

docker-compose.yml:

```yml
services:
  fpm:
    container_name: fpm
    image: php:7.2-fpm
    environment:
      - MH_SENDMAIL_SMTP_ADDR="mailhog:1025"
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
```
php.ini:
```conf
sendmail_path = /usr/local/bin/mhsendmail
```
test call run from fpm container:
```bash
php -r "\$from = \$to = 'your.emailaddress@gmail.com'; \$x = mail(\$to, 'subject'.time(), 'Hello World', 'From: '. \$from); var_dump(\$x);"
```
result:
```bash
error sending mail
dial tcp 127.0.0.1:1025: getsockopt: connection refused
bool(false)
```
running the same test from host works fine.
